brew install "awscli"
brew install "colima"
brew install "coreutils"
brew install "curl"
brew install "docker"
brew install "docker-buildx"
brew install "docker-compose"
brew install "fzf"
brew install "gawk"
brew install "gh"
brew install "ghq"
brew install "git"
brew install "gnu-sed"
brew install "gnu-tar"
brew install "grep"
brew install "jq"
brew install "make"
brew install "mas"
brew install "mise"
brew install "ripgrep"

brew install --cask "aws-vault"
brew install --cask "discord"
brew install --cask "google-chrome"
brew install --cask "karabiner-elements"
brew install --cask "obsidian"
brew install --cask "raycast"
brew install --cask "visual-studio-code"
brew install --cask "warp"
brew install --cask "zoom"
