brew install "awscli"
brew install "coreutils"
brew install "curl"
brew install "fzf"
brew install "gh"
brew install "ghq"
brew install "git"
brew install "jq"
brew install "make"
brew install "mas"
brew install "grep"
brew install "mise"
brew install "gnu-sed"
brew install "gawk"
brew install "gnu-tar"

brew install --cask "aws-vault"
brew install --cask "discord"
brew install --cask "google-chrome"
brew install --cask "karabiner-elements"
brew install --cask "obsidian"
brew install --cask "raycast"
brew install --cask "visual-studio-code"
brew install --cask "warp"
brew install --cask "zoom"
